// This repository intentionally stores legal metadata separately from evaluation code.
// It represents preliminary screening rules only; an officer remains responsible for a final decision.

export const PCR_CONSOLIDATED_SOURCE = 'https://consumeraffairs.gov.in/public/upload/admin/cmsfiles/whatsnews/Book_on_Legal_Metrology_Packaged_Commodities_Rules%2C2011_with_all_amendments_whatsnews.pdf';
export const PCR_2021_AMENDMENT_SOURCE = 'https://consumeraffairs.gov.in/public/upload/admin/cmsfiles/whatsnews/The_Legal_Metrology_Packaged_Commodities_Amendment_Rule%2C_2021_whatsnews.pdf';
export const PCR_2026_ECOMMERCE_SOURCE = 'https://consumeraffairs.gov.in/public/upload/files/2026.02.13%20PCR%201st%20COO%20Filter%20on%20e-commerce%20websites_1771231030.pdf';
export const PCR_2026_ECOMMERCE_FUTURE_SOURCE = 'https://consumeraffairs.gov.in/public/upload/files/2026.4.27%20PCR%202nd%20COO%20from%201.7.2027_1777348487.pdf';
export const PCR_OUTER_PACKAGE_ADVISORY_SOURCE = 'https://consumeraffairs.gov.in/public/upload/admin/cmsfiles/whatsnews/Declaration_of_mandatory_information_on_the_outer_retail_package_-_reg._whatsnews.pdf';

const sourceDocument = 'Legal Metrology (Packaged Commodities) Rules, 2011 (as amended)';
const sourceUrl = PCR_CONSOLIDATED_SOURCE;
const rule = (definition) => ({ version: '2026-09-20', effective_from: '2011-04-01', effective_to: null, active: true, human_review_required: true, source_document: sourceDocument, source_url: sourceUrl, ...definition });

// `extraction_key` documents the Gemini field needed by a rule. Rules with no current
// extraction key remain in the repository but are not automatically treated as missing.
export const CORE_RULES = [
  rule({ id: 'lmpcr-6-1-a-responsible-party', rule_code: 'LMPCR-R6-1-A-RESPONSIBLE-PARTY', rule_number: 'Rule 6(1)(a)', rule_name: 'Responsible party name and address', requirement: 'Declare the name and address of the manufacturer, packer, or importer, as applicable.', description: 'Screens the extracted responsible-party declaration for visible presence.', category: 'IDENTITY', applicability_conditions: { retail_package: true }, validation_type: 'PRESENCE', extraction_key: 'manufacturerPackerImporter', severity: 'HIGH' }),
  rule({ id: 'lmpcr-6-1-a-address-review', rule_code: 'LMPCR-R6-1-A-ADDRESS', rule_number: 'Rule 6(1)(a)', rule_name: 'Responsible party address adequacy', requirement: 'The applicable responsible party declaration includes an address.', description: 'Address completeness requires an officer because an image extraction cannot establish whether an address is legally adequate.', category: 'IDENTITY', applicability_conditions: { retail_package: true }, validation_type: 'MANUAL_REVIEW', extraction_key: 'manufacturerPackerImporter', severity: 'MEDIUM' }),
  rule({ id: 'lmpcr-6-country-origin-imported', rule_code: 'LMPCR-R6-COUNTRY-ORIGIN', rule_number: 'Rule 6 (imported products)', rule_name: 'Country of origin for imported product', requirement: 'Declare country of origin for an imported product.', description: 'Only applies when the product is confirmed as imported.', category: 'ORIGIN', applicability_conditions: { import_status: 'IMPORTED' }, validation_type: 'PRESENCE', extraction_key: 'countryOfOrigin', severity: 'HIGH', source_url: PCR_OUTER_PACKAGE_ADVISORY_SOURCE, source_section: 'Rule 6; Department advisory dated 18.01.2023' }),
  rule({ id: 'lmpcr-6-1-b-generic-name', rule_code: 'LMPCR-R6-1-B-GENERIC-NAME', rule_number: 'Rule 6(1)(b)', rule_name: 'Common or generic commodity name', requirement: 'Declare the common or generic name of the commodity.', description: 'Screens the extracted common/generic-name declaration for visible presence.', category: 'IDENTITY', applicability_conditions: { retail_package: true }, validation_type: 'PRESENCE', extraction_key: 'productName', severity: 'HIGH' }),
  rule({ id: 'lmpcr-6-1-c-net-quantity', rule_code: 'LMPCR-R6-1-C-NET-QUANTITY', rule_number: 'Rule 6(1)(c)', rule_name: 'Net quantity declaration', requirement: 'Declare net quantity in a standard unit of weight or measure, or in number.', description: 'Screens the extracted net-quantity declaration for visible presence.', category: 'QUANTITY', applicability_conditions: { retail_package: true }, validation_type: 'PRESENCE', extraction_key: 'netQuantity', severity: 'HIGH' }),
  rule({ id: 'lmpcr-6-1-c-net-quantity-format', rule_code: 'LMPCR-R6-1-C-NET-QUANTITY-FORMAT', rule_number: 'Rule 6(1)(c)', rule_name: 'Net quantity unit format', requirement: 'State net quantity using a standard weight, measure, or number unit.', description: 'A narrow syntax screen only; it does not verify actual contents, quantity tolerance, or all permitted unit representations.', category: 'QUANTITY', applicability_conditions: { retail_package: true }, validation_type: 'FORMAT', extraction_key: 'netQuantity', validator: 'METRIC_QUANTITY', severity: 'MEDIUM' }),
  rule({ id: 'lmpcr-6-1-d-month-year', rule_code: 'LMPCR-R6-1-D-MONTH-YEAR', rule_number: 'Rule 6(1)(d)', rule_name: 'Month and year declaration', requirement: 'Declare the applicable month and year of manufacture, packing, or import.', description: 'The applicable date type and statutory exception must be confirmed from product context.', category: 'DATE', applicability_conditions: { retail_package: true, date_exception: false }, validation_type: 'PRESENCE', extraction_key: 'packingDate', severity: 'HIGH' }),
  rule({ id: 'lmpcr-6-1-d-date-format', rule_code: 'LMPCR-R6-1-D-DATE-FORMAT', rule_number: 'Rule 6(1)(d)', rule_name: 'Month and year format', requirement: 'The applicable declaration must include a month and year.', description: 'Syntax screen for a month/year; it cannot determine the correct event date.', category: 'DATE', applicability_conditions: { retail_package: true, date_exception: false }, validation_type: 'FORMAT', extraction_key: 'packingDate', validator: 'MONTH_YEAR', severity: 'MEDIUM' }),
  rule({ id: 'lmpcr-6-1-da-best-before', rule_code: 'LMPCR-R6-1-DA-BEST-BEFORE', rule_number: 'Rule 6(1)(da)', rule_name: 'Best-before or use-by declaration', requirement: 'Declare best-before or use-by date, month and year when the commodity may become unfit for human consumption, unless another law provides for it.', description: 'Conditional rule; category and other-law coverage cannot be inferred safely from the current image contract.', category: 'DATE', applicability_conditions: { may_become_unfit_for_human_consumption: true, covered_by_other_law: false }, validation_type: 'PRESENCE', extraction_key: 'bestBefore', severity: 'HIGH' }),
  rule({ id: 'lmpcr-6-1-e-mrp', rule_code: 'LMPCR-R6-1-E-MRP', rule_number: 'Rule 6(1)(e)', rule_name: 'Retail sale price / MRP', requirement: 'Declare the retail sale price in Indian currency; retail sale price is inclusive of all taxes.', description: 'Screens the extracted retail-sale-price declaration for visible presence.', category: 'PRICE', applicability_conditions: { retail_package: true }, validation_type: 'PRESENCE', extraction_key: 'mrp', severity: 'HIGH', source_url: PCR_2021_AMENDMENT_SOURCE, source_section: 'Rule 6(1)(e), as amended by G.S.R. 779(E)' }),
  rule({ id: 'lmpcr-6-1-e-mrp-format', rule_code: 'LMPCR-R6-1-E-MRP-FORMAT', rule_number: 'Rule 6(1)(e)', rule_name: 'Retail sale price currency format', requirement: 'State the retail sale price in Indian currency.', description: 'Syntax screen only; it does not prove tax treatment, price accuracy, or a sale above MRP.', category: 'PRICE', applicability_conditions: { retail_package: true }, validation_type: 'FORMAT', extraction_key: 'mrp', validator: 'INDIAN_CURRENCY_PRICE', severity: 'MEDIUM', source_url: PCR_2021_AMENDMENT_SOURCE, source_section: 'Rule 6(1)(e), as amended by G.S.R. 779(E)' }),
  rule({ id: 'lmpcr-6-consumer-care', rule_code: 'LMPCR-R6-CONSUMER-CARE', rule_number: 'Rule 6', rule_name: 'Consumer care details', requirement: 'Declare consumer care details.', description: 'Screens the extracted consumer-care declaration for visible presence; adequacy is reviewed by an officer.', category: 'CONSUMER_CONTACT', applicability_conditions: { retail_package: true }, validation_type: 'PRESENCE', extraction_key: 'consumerCare', severity: 'HIGH', source_url: PCR_OUTER_PACKAGE_ADVISORY_SOURCE, source_section: 'Rule 6; Department advisory dated 18.01.2023' }),
  rule({ id: 'lmpcr-6-consumer-care-review', rule_code: 'LMPCR-R6-CONSUMER-CARE-REVIEW', rule_number: 'Rule 6', rule_name: 'Consumer care detail adequacy', requirement: 'Consumer care information must be adequate for consumer contact.', description: 'Current extraction aggregates contact information and cannot establish statutory sufficiency or whether it is operational.', category: 'CONSUMER_CONTACT', applicability_conditions: { retail_package: true }, validation_type: 'MANUAL_REVIEW', extraction_key: 'consumerCare', severity: 'MEDIUM', source_url: PCR_OUTER_PACKAGE_ADVISORY_SOURCE, source_section: 'Rule 6; Department advisory dated 18.01.2023' }),
  rule({ id: 'lmpcr-6-1-f-dimensions', rule_code: 'LMPCR-R6-1-F-DIMENSIONS', rule_number: 'Rule 6(1)(f)', rule_name: 'Dimensions where size is relevant', requirement: 'Declare relevant dimensions, including each different piece where applicable.', description: 'Conditional rule requiring product/category context and a dimensions extraction field.', category: 'DIMENSIONS', applicability_conditions: { size_relevant: true }, validation_type: 'PRESENCE', extraction_key: 'dimensions', severity: 'MEDIUM' }),
  rule({ id: 'lmpcr-6-11-unit-sale-price', rule_code: 'LMPCR-R6-11-UNIT-SALE-PRICE', rule_number: 'Rule 6(11)', rule_name: 'Unit sale price', requirement: 'Declare unit sale price in rupees using the prescribed basis for the net quantity.', description: 'Requires product context, net quantity, and a unit-sale-price extraction field.', category: 'PRICE', applicability_conditions: { wholesale_package: false }, validation_type: 'PRESENCE', extraction_key: 'unitSalePrice', severity: 'MEDIUM', source_url: PCR_2021_AMENDMENT_SOURCE, source_section: 'Rule 6(11), inserted by G.S.R. 779(E)' }),
  rule({ id: 'lmpcr-6-11-unit-sale-price-format', rule_code: 'LMPCR-R6-11-UNIT-SALE-PRICE-FORMAT', rule_number: 'Rule 6(11)', rule_name: 'Unit sale price basis', requirement: 'State unit sale price in rupees per the prescribed gram, kilogram, centimetre, metre, number, millilitre, or litre basis.', description: 'Syntax screen only; correct basis depends on verified net quantity.', category: 'PRICE', applicability_conditions: { wholesale_package: false }, validation_type: 'FORMAT', extraction_key: 'unitSalePrice', validator: 'UNIT_SALE_PRICE', severity: 'LOW', source_url: PCR_2021_AMENDMENT_SOURCE, source_section: 'Rule 6(11), inserted by G.S.R. 779(E)' }),
  rule({ id: 'lmpcr-4-group-package', rule_code: 'LMPCR-R4-GROUP-PACKAGE', rule_number: 'Rule 4(2)', rule_name: 'Promotional group package declarations', requirement: 'Every retail package in a promotional retail group must comply with Rule 6.', description: 'Requires images/data for each inner retail package.', category: 'PACKAGE_TYPE', applicability_conditions: { promotional_group_package: true }, validation_type: 'MANUAL_REVIEW', extraction_key: 'groupPackageEvidence', severity: 'MEDIUM', source_url: PCR_2021_AMENDMENT_SOURCE, source_section: 'Rule 4(2), inserted by G.S.R. 779(E)' }),
  rule({ id: 'lmpcr-9-legibility', rule_code: 'LMPCR-R9-LEGIBILITY', rule_number: 'Rule 9(1)(a)', rule_name: 'Legibility and prominence', requirement: 'Required declarations must be legible and prominent.', description: 'Image pixels cannot establish statutory physical type size, contrast, or package-panel dimensions; this always needs officer review.', category: 'READABILITY', applicability_conditions: { retail_package: true }, validation_type: 'READABILITY_REVIEW', extraction_key: 'readability', severity: 'MEDIUM' }),
  rule({ id: 'lmpcr-6-10-ecommerce-declarations', rule_code: 'LMPCR-R6-10-ECOMMERCE-DECLARATIONS', rule_number: 'Rule 6(10)', rule_name: 'E-commerce mandatory declarations', requirement: 'An e-commerce entity must ensure the specified mandatory declarations are displayed on the digital/electronic network.', description: 'Requires structured listing data; package-image extraction cannot validate an online listing.', category: 'ECOMMERCE', applicability_conditions: { sales_channel: 'ECOMMERCE' }, validation_type: 'MANUAL_REVIEW', extraction_key: 'listingDeclarations', severity: 'HIGH' }),
  rule({ id: 'lmpcr-6-10a-ecommerce-origin-filter-2026', rule_code: 'LMPCR-R6-10A-ECOMMERCE-ORIGIN-FILTER', rule_number: 'Rule 6(10A)', rule_name: 'Imported-product origin filter', requirement: 'An e-commerce entity selling imported products must provide a searchable and sortable country-of-origin filter.', description: 'Current version effective 01.07.2026; it requires marketplace capability data, not package-image extraction.', category: 'ECOMMERCE', applicability_conditions: { sales_channel: 'ECOMMERCE', import_status: 'IMPORTED' }, validation_type: 'MANUAL_REVIEW', extraction_key: 'countryOfOriginFilter', severity: 'MEDIUM', effective_from: '2026-07-01', effective_to: '2027-06-30', source_url: PCR_2026_ECOMMERCE_SOURCE, source_document: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2026', source_section: 'Rule 6(10A)' }),
  rule({ id: 'lmpcr-6-10a-ecommerce-origin-filter-2027', rule_code: 'LMPCR-R6-10A-ECOMMERCE-ORIGIN-FILTER-2027', rule_number: 'Rule 6(10A)', rule_name: 'Imported-product origin filter', requirement: 'An e-commerce entity offering an imported product for sale must ensure its listing contains a searchable and sortable country-of-origin filter.', description: 'Future version, effective 01.07.2027; retained so the rule version is explicit.', category: 'ECOMMERCE', applicability_conditions: { sales_channel: 'ECOMMERCE', import_status: 'IMPORTED' }, validation_type: 'MANUAL_REVIEW', extraction_key: 'countryOfOriginFilter', severity: 'MEDIUM', active: false, effective_from: '2027-07-01', source_url: PCR_2026_ECOMMERCE_FUTURE_SOURCE, source_document: 'Legal Metrology (Packaged Commodities) Second Amendment Rules, 2026', source_section: 'Rule 6(10A)' }),
];
