import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Check, ExternalLink, ShieldCheck, Sparkles } from 'lucide-react';
import { ruleSummaries } from '../../data/mockData';

export function Landing() {
  return <main className="landing"><nav><div className="brand"><ShieldCheck /> LabelGuard</div><div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}><Link className="btn ghost" to="/rules"><BookOpen size={16} /> Official Rules</Link><Link className="btn primary" to="/login">Sign In</Link></div></nav><section className="landing-hero"><div className="hero-pill"><Sparkles size={15} /> Next-Gen Legal Metrology Verification (SIH 2026)</div><h1>Smart Label Compliance for Every <em>Packaged Commodity</em></h1><p>AI-assisted declaration extraction and real-time rule verification designed for Metrology Officers, FMCG manufacturers, and e-commerce sellers.</p><div className="hero-cta"><Link className="btn primary lg" to="/login">Start Compliance Check <ArrowRight size={18} /></Link><Link className="btn outline lg" to="/rules">Browse Statutory Rules</Link></div><div className="hero-metrics-bar"><div className="metric-item"><b className="num">99.4%</b><span>OCR Extraction Accuracy</span></div><div className="metric-item"><b className="num">&lt; 2.5s</b><span>Average Verification Speed</span></div><div className="metric-item"><b className="num">100%</b><span>LMPC Rule Alignment</span></div></div></section><section className="landing-section"><div className="section-head"><span className="eyebrow">A SIMPLE, AUDITABLE PROCESS</span><h2>From label upload to inspection insight in seconds</h2></div><div className="steps">{[['01', 'Upload / Scan', 'Capture image of product packaging or display panel.'], ['02', 'Extract Declarations', 'Precision OCR extracts Net Qty, MRP, Packer, and Origin.'], ['03', 'Apply Legal Rules', 'Instant evaluation against Legal Metrology (PCR) Rules, 2011.'], ['04', 'Act with Confidence', 'Export official reports, flag violations, or request re-inspections.']].map((item) => <article key={item[0]}><b className="num">{item[0]}</b><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></section></main>;
}

export function PublicRulesPage() {
  return <div className="landing" style={{ minHeight: '100vh', background: 'var(--bg-app)' }}><nav><Link className="brand" to="/"><ShieldCheck /> LabelGuard</Link><div style={{ display: 'flex', gap: '12px' }}><Link className="btn outline" to="/">Home</Link><Link className="btn primary" to="/login">Sign In</Link></div></nav><main style={{ maxWidth: '1040px', margin: '0 auto', padding: '40px 24px' }}><div className="page-title" style={{ padding: '0 0 24px' }}><div><span className="eyebrow">STATUTORY LEGAL FRAMEWORK</span><h1>Official Rules & Packaging Acts</h1><p>Plain-language statutory summaries and links to official documentation.</p></div></div><section className="rules-list">{ruleSummaries.map((rule) => <article className="panel" key={rule.id} style={{ margin: '18px 0', padding: '28px' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}><span className="badge good">{rule.subtitle}</span><span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>{rule.source}</span></div><h2 style={{ fontSize: '22px', margin: '6px 0 10px' }}>{rule.title}</h2><div style={{ background: 'var(--bg-subtle)', padding: '14px 18px', borderRadius: 'var(--radius-sm)', borderLeft: '4px solid var(--brand-primary)', marginBottom: '18px' }}><strong style={{ display: 'block', color: 'var(--text-main)', marginBottom: '4px' }}>Statutory Purpose:</strong><span style={{ color: 'var(--text-muted)', fontSize: '14px' }}>{rule.simpleTakeaway}</span></div><h3 style={{ fontSize: '15px', color: 'var(--text-main)', marginBottom: '10px' }}>Mandatory Compliance Points:</h3><ul style={{ listStyle: 'none', padding: 0, margin: '0 0 20px' }}>{rule.keyPoints.map((point, index) => <li key={index} style={{ display: 'flex', gap: '10px', alignItems: 'flex-start', padding: '5px 0', fontSize: '14px', color: 'var(--text-muted)' }}><Check size={16} color="var(--status-good)" style={{ flexShrink: 0, marginTop: '3px' }} /><span>{point}</span></li>)}</ul><div style={{ borderTop: '1px solid var(--border-light)', paddingTop: '16px' }}><a className="btn outline" href={rule.url} target="_blank" rel="noopener noreferrer">Open Official Reference Portal <ExternalLink size={13} /></a></div></article>)}</section></main></div>;
}
